# .github/workflows/deploy.yml
name: Deploy to Railway

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Railway CLI
      run: |
        curl -sSL https://railway.app/install.sh | sh
    
    - name: Deploy to Railway
      run: |
        railway login --token ${{ secrets.RAILWAY_TOKEN }}
        railway up --service nava-api
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}